[build]
  base    = "src"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from   = "/legal/*"
  to     = "https://legalhub.pecuvate.com/share/empowr/efn/:splat"
  status = 200
  force  = true
